MODULE TIMING_MOD

USE EC_PARKIND, ONLY: JPRD

REAL(JPRD), PUBLIC, ALLOCATABLE :: T_EVENT(:)
INTEGER, PUBLIC, ALLOCATABLE :: T_TYPE(:), T_BATCH(:), T_STAGE(:)
INTEGER, PUBLIC :: TCOUNT
LOGICAL, PUBLIC :: TENABLE
INTEGER, PUBLIC, PARAMETER :: TCOMM1 = 1
INTEGER, PUBLIC, PARAMETER :: TCOMM2 = 2
INTEGER, PUBLIC, PARAMETER :: TCOMM3 = 3
INTEGER, PUBLIC, PARAMETER :: TCOMP1 = 4
INTEGER, PUBLIC, PARAMETER :: TCOMP2 = 5
INTEGER, PUBLIC, PARAMETER :: TCOMP3 = 6
INTEGER, PUBLIC, PARAMETER :: TCOMP4 = 7
INTEGER, PUBLIC, PARAMETER :: TPACK1 = 8
INTEGER, PUBLIC, PARAMETER :: TPACK2 = 9
INTEGER, PUBLIC, PARAMETER :: TRECV1 = 10
INTEGER, PUBLIC, PARAMETER :: TUNPK1 = 11
INTEGER, PUBLIC, PARAMETER :: TUNPK2 = 12

CONTAINS

FUNCTION GET_TIME()

USE MPI, ONLY: MPI_WTIME

IMPLICIT NONE

REAL(JPRD) :: GET_TIME

GET_TIME = MPI_WTIME()

END FUNCTION GET_TIME

END MODULE TIMING_MOD
